[[sgtsnepi]]
arch = "i686"
git-tree-sha1 = "d579e5f352b34c0ebb774800030df868548c23da"
libc = "glibc"
os = "linux"

    [[sgtsnepi.download]]
    sha256 = "b59737cb5cf966641acfe9b711ae658d9e842c07f7690b3c199df7b6134fd02c"
    url = "https://github.com/JuliaBinaryWrappers/sgtsnepi_jll.jl/releases/download/sgtsnepi-v2.0.0+0/sgtsnepi.v2.0.0.i686-linux-gnu.tar.gz"
[[sgtsnepi]]
arch = "i686"
git-tree-sha1 = "86cf5ee4e985f901b99f16eee9c7a09635a80ffb"
libc = "musl"
os = "linux"

    [[sgtsnepi.download]]
    sha256 = "fd0ccfa4f2dae87e825067b80376a9893677a6e7454e40340782913858501e7b"
    url = "https://github.com/JuliaBinaryWrappers/sgtsnepi_jll.jl/releases/download/sgtsnepi-v2.0.0+0/sgtsnepi.v2.0.0.i686-linux-musl.tar.gz"
[[sgtsnepi]]
arch = "x86_64"
git-tree-sha1 = "fc41a0b85a58b8e54510707db829eac66b8f80b7"
os = "macos"

    [[sgtsnepi.download]]
    sha256 = "6fe0fe1d5215c0e60454e7c8112927335b762521e5f2cd892df83f19475e9e5f"
    url = "https://github.com/JuliaBinaryWrappers/sgtsnepi_jll.jl/releases/download/sgtsnepi-v2.0.0+0/sgtsnepi.v2.0.0.x86_64-apple-darwin.tar.gz"
[[sgtsnepi]]
arch = "x86_64"
git-tree-sha1 = "bd6322ff146661a4fe954133f14c87136dfe132b"
libc = "glibc"
os = "linux"

    [[sgtsnepi.download]]
    sha256 = "310afa397008b77d35fc014525d4b2d2193653af423f10b49914c4284ccbfca2"
    url = "https://github.com/JuliaBinaryWrappers/sgtsnepi_jll.jl/releases/download/sgtsnepi-v2.0.0+0/sgtsnepi.v2.0.0.x86_64-linux-gnu.tar.gz"
[[sgtsnepi]]
arch = "x86_64"
git-tree-sha1 = "5d708d9d848597e8a62fdea8c52c0c12bebb30af"
libc = "musl"
os = "linux"

    [[sgtsnepi.download]]
    sha256 = "90aeecc25ddfda03d91852246439270c0bb12a4548faeebfa8125d3c89a31b06"
    url = "https://github.com/JuliaBinaryWrappers/sgtsnepi_jll.jl/releases/download/sgtsnepi-v2.0.0+0/sgtsnepi.v2.0.0.x86_64-linux-musl.tar.gz"
[[sgtsnepi]]
arch = "x86_64"
git-tree-sha1 = "40a010704fad476d8073671724b10c4a17c476b6"
os = "freebsd"

    [[sgtsnepi.download]]
    sha256 = "4581460ea842c781e2cd0d5c43a5d297b5d1713afe63ae04cb1b64fe77b73548"
    url = "https://github.com/JuliaBinaryWrappers/sgtsnepi_jll.jl/releases/download/sgtsnepi-v2.0.0+0/sgtsnepi.v2.0.0.x86_64-unknown-freebsd.tar.gz"
