# Autogenerated wrapper script for sgtsnepi_jll for x86_64-w64-mingw32-cxx11
export libsgtsnepi

using FFTW_jll
JLLWrappers.@generate_wrapper_header("sgtsnepi")
JLLWrappers.@declare_library_product(libsgtsnepi, "libsgtsnepi-0.dll")
function __init__()
    JLLWrappers.@generate_init_header(FFTW_jll)
    JLLWrappers.@init_library_product(
        libsgtsnepi,
        "bin\\libsgtsnepi-0.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
